baseURL = "http://kidscancode.org/godot_recipes/"
publishDir = "../docs"
languageCode = "en-us"
title = "Godot Recipes by KidsCanCode"
theme = "hugo-theme-learn-cb"
pygmentsStyle = "dracula"
pygmentsCodeFences = true
googleAnalytics = "UA-39851424-1"
disqusShortname = "kidscancode"

[params]
    disableNextPrev = true
    themeVariant = "green"
    disableInlineCopyToClipBoard = true

[outputs]
    home = [ "HTML", "RSS", "JSON"]